name: motionbert
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - coverage
  - easydict
  - flake8
  - imageio-ffmpeg
  - interrogate
  - ipdb
  - isort
  - json_tricks
  - matplotlib
  - munkres
  - parameterized
  - pillow
  - prettytable
  - protobuf=3.19.6
  - pytest
  - pytest-runner
  - pytorch-metric-learning
  - requests
  - requests=2.28.2
  - rich=13.4.2
  - scipy
  - setuptools=60.2.0
  - tensorboard
  - tensorboardx
  - tqdm
  - urllib3=1.26.18
  - xdoctest
  - yapf
  - pip
  - pip:
    - chumpy
    - nvitop
    - open3d
    - roma
    - smplx[all]
    - torch-tb-profiler
    - xtcocotools
    - -r mmlab_requirements.txt
variables:
  PYTORCH_ENABLE_MPS_FALLBACK: '1'